### ISSUE TITLE
Handle missing description

### ISSUE THREAD

**Issue by starsep** [ZeLonewolf/osm-wikidata-greasemonkey#2]
Example: https://osm.org/node/566725213

![image](https://github.com/ZeLonewolf/osm-wikidata-greasemonkey/assets/2798728/7322c900-6483-4440-930c-912813770f9d)

I think it's caused by missing logo in Wikidata: https://www.wikidata.org/wiki/Q108586693

**Comment by ZeLonewolf** [comment]
The "undefined" is actually caused by there being no description, which is a case I did not consider and will fix by suppressing the box entirely.

The logo is not there because that wikidata item lacks a P8972 ([small logo or icon](https://www.wikidata.org/wiki/Property:P8972)) or [logo image](https://www.wikidata.org/wiki/Property:P154) claim.
